apiVersion: apps/v1
kind: Service
metadata:
  name: grpc-chat-service
  labels:
    app: grpc-chat-label
spec:
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  selector:
    app: grpc-chat-label
